### ISSUE TITLE
Release for the obtained summary for 40K

### ISSUE THREAD

**Issue by ermu2001** [ShareGPT4Omni/ShareGPT4Video#12]
Hi, really great work, luv this data pipeline!

Do we have plans to release the summary results from GPT4V or instruction tuning data!

**Comment by xiaoachen98** [comment]
> Hi, really great work, luv this data pipeline!
> 
> Do we have plans to release the summary results from GPT4V or instruction tuning data!

Thank you for your attention. Not sure what you mean by summary. You can find our jsonl file [here](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video), where the last element in the captions keyword is the final summary caption.
