### ISSUE TITLE
question about "Batch inference code for captioner"

### ISSUE THREAD

**Issue by zZer0o** [ShareGPT4Omni/ShareGPT4Video#13]
Thanks for your work!

Could you explain which part of the inference stage in ShareCaptioner-Video can be modified for batch inference mode? Or maybe I have misunderstood the meaning of "batch inference". The code to be released is actually for batch inference of multiple videos, rather than performing batch inference in a single inference process.

**Comment by xiaoachen98** [comment]
> Thanks for your work!
> 
> Could you explain which part of the inference stage in ShareCaptioner-Video can be modified for batch inference mode? Or maybe I have misunderstood the meaning of "batch inference". The code to be released is actually for batch inference of multiple videos, rather than performing batch inference in a single inference process.

It's for annotating a batch of videos at once under the sliding and fast captioning mode.
