### ISSUE TITLE
"num_frames = 16" in run.py means  taking out an average of 16 frames of a video?

### ISSUE THREAD

**Issue by NuyoaHygge** [ShareGPT4Omni/ShareGPT4Video#15]
https://github.com/ShareGPT4Omni/ShareGPT4Video/blob/195fab77fd8186feea20e315e7a626c4fa206cff/run.py#L153C5-L153C15

"num_frames = 16" in run.py means  taking out an average of 16 frames of a video? This is inconsistent with the paper's claim of Semantic-aware Key-frame Extraction. Am I misunderstanding?

**Comment by xiaoachen98** [comment]
> https://github.com/ShareGPT4Omni/ShareGPT4Video/blob/195fab77fd8186feea20e315e7a626c4fa206cff/run.py#L153C5-L153C15
> 
> "num_frames = 16" in run.py means taking out an average of 16 frames of a video? This is inconsistent with the paper's claim of Semantic-aware Key-frame Extraction. Am I misunderstanding?

It's for running our ShareGPT4Video-8B rather than the ShareCaptioner-Video.
