### ISSUE TITLE
Great work! What is the difference between these two models? 

### ISSUE THREAD

**Issue by WilTay1** [ShareGPT4Omni/ShareGPT4Video#18]
![image](https://github.com/ShareGPT4Omni/ShareGPT4Video/assets/133484736/863b3c6f-f3ac-4975-a7c8-918d3516b26e)

**Comment by xiaoachen98** [comment]
> ![image](https://private-user-images.githubusercontent.com/133484736/342995365-863b3c6f-f3ac-4975-a7c8-918d3516b26e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODIzNzQsIm5iZiI6MTcxOTM4MjA3NCwicGF0aCI6Ii8xMzM0ODQ3MzYvMzQyOTk1MzY1LTg2M2IzYzZmLWYzYWMtNDk3NS1hN2M4LTkxOGQzNTE2YjI2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNjA3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODgzNTAxYjNkNjMzMGM4NWM1NmRkNGMzOTdiNDIwOWI1Mzk3NjRlYWVjZWY0Nzc1ZDRiYzQ4MWMyZDVkZDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AuzKhFWG4qvZPlHLSrxo65OUvu104WlEInSro-2DHzo)

We use LLaVA-Next-8B for our ShareGPT4Video-8B for easy reproduction. We choose InternLM-XComposer2-4KHD which can handle a wide range of resolutions and aspect ratios of images to perform a general captioner for various videos.
