### ISSUE TITLE
Inference returns null str.

### ISSUE THREAD

**Issue by ChawDoe** [ShareGPT4Omni/ShareGPT4Video#2]
<img width="654" alt="image" src="https://github.com/ShareGPT4Omni/ShareGPT4Video/assets/25716030/b08a4c65-91bf-4641-84ed-6b433fcad9f9">
load model successfully but failed to infer. 
the returned generation result is null str.

**Comment by hkunzhe** [comment]
@ChawDoe Have you solved this issue, and would you be willing to share the code for inference?

**Comment by xiaoachen98** [comment]
> <img alt="image" width="654" src="https://private-user-images.githubusercontent.com/25716030/337611814-b08a4c65-91bf-4641-84ed-6b433fcad9f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDgyNTMsIm5iZiI6MTcxODIwNzk1MywicGF0aCI6Ii8yNTcxNjAzMC8zMzc2MTE4MTQtYjA4YTRjNjUtOTFiZi00NjQxLTg0ZWQtNmI0MzNmY2FkOWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE1NTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NDI0Nzk3MWVjZWRiMTZjOWQ5Y2YyZmQ5YjM1YzBjYWVlOTI5MGUzM2VkMzk5ZWM3OWFmZTViYjgxOTA1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kw0PPP5SkFJhrg9SJtiO8IgMABbfnNA4N680vpMkOHg"> load model successfully but failed to infer. the returned generation result is null str.

Our captioner is available now! Enjoy it!
