### ISSUE TITLE
Question about "slide_captioner_lmdeploy.py"

### ISSUE THREAD

**Issue by Joanna0123** [ShareGPT4Omni/ShareGPT4Video#22]
Thanks for your work!

I have a question about lines 63-66 in `captioner/slide_captioner_lmdeploy.py`. In the text prompt, it seems that two frames should be provided to the model. However, only one `curr_img` is returned. I would like to confirm if this part of the code implementation needs to be corrected, or if my understanding is incorrect.

**Comment by zehuichen123** [comment]
Thanks for your interest. Actually, for each frame, our prompt consists of two parts: a previously generated description on the last frame, and the requests to generate a caption by considering the image from the current frame as well as the previous description. Therefore, there is only one image input at each iteration.
