### ISSUE TITLE
Caption data of ShareGPT4Video dataset

### ISSUE THREAD

**Issue by Marlod390** [ShareGPT4Omni/ShareGPT4Video#4]
Dear authors,

thank your for your great work. I want to check the text content of your ShareGPT4Video dataset, but I only found videos on huggingface. Where can I find the corresponding captions?

**Comment by xiaoachen98** [comment]
> Dear authors,
> 
> thank your for your great work. I want to check the text content of your ShareGPT4Video dataset, but I only found videos on huggingface. Where can I find the corresponding captions?

Sorry for the delay. The captions are right [here](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/blob/main/sharegpt4video_40k.jsonl)
