### ISSUE TITLE
Map video_id (pexels/pixabay) back to its original url id

### ISSUE THREAD

**Issue by hkunzhe** [ShareGPT4Omni/ShareGPT4Video#5]
Since I have downloaded some pexels and pixabay videos already and used the original video url id (https://www.pexels.com/video/1321208/) as the video id, I wanna know how the video id in the https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/blob/main/sharegpt4video_40k.jsonl is generated, can I map it back to the video id corresponding to the url?

**Comment by Wiselnn570** [comment]
> Since I have downloaded some pexels and pixabay videos already and used the original video url id (https://www.pexels.com/video/1321208/) as the video id, I wanna know how the video id in the https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/blob/main/sharegpt4video_40k.jsonl is generated, can I map it back to the video id corresponding to the url?

Sorry, our data team didn't provide the mapping. Apologies for the inconvenience.
