### ISSUE TITLE
Demos about ShareCaptioner-Video

### ISSUE THREAD

**Issue by hkunzhe** [ShareGPT4Omni/ShareGPT4Video#6]
Hi, Thanks for this great project! I noticed that currently in `run.py`, only the usage of sharegpt4video-8b is demonstrated, and not include ShareCaptioner-Video. Could you provide more examples demonstrating how to utilize this model in each of its four roles?

**Comment by xiaoachen98** [comment]
> Hi, Thanks for this great project! I noticed that currently in `run.py`, only the usage of sharegpt4video-8b is demonstrated, and not include ShareCaptioner-Video. Could you provide more examples demonstrating how to utilize this model in each of its four roles?

work in progress, pls stay in tuned
