### ISSUE TITLE
Missing "panda"?

### ISSUE THREAD

**Issue by linzhiqiu** [ShareGPT4Omni/ShareGPT4Video#8]
I noticed that the huggingface dataset page does not provide the panda folder. Could you provide us with the instructions for downloading the corresponding videos?

**Comment by Wiselnn570** [comment]
> I noticed that the huggingface dataset page does not provide the panda folder. Could you provide us with the instructions for downloading the corresponding videos?

Hi, @linzhiqiu  ! You can download panda videos required for this dataset from [https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/tree/main/user_download/download_panda_video.py](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/blob/main/user_download/download_panda_video.py)
Best wishes.

**Comment by linzhiqiu** [comment]
Should the filenames in "sharegpt4video_40k.jsonl" be updated accordingly? Specifically the field "video_path"

**Comment by linzhiqiu** [comment]
In addition, I noticed that it will also download the raw videos -- will this require very large storage? Is there an estimated storage cost?

**Comment by xiaoachen98** [comment]
> In addition, I noticed that it will also download the raw videos -- will this require very large storage? Is there an estimated storage cost?

We are working on clipping the used Panda videos and packing them in one zip file. Please stay tuned.

**Comment by geonm** [comment]
@xiaoachen98

I attempted to download 27,092 videos using the [panda.csv](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/blob/main/user_download/panda.csv) file, but only 15,537 videos were successfully downloaded. 

I'm looking forward to _the one zip file_.

**Comment by linzhiqiu** [comment]
> @xiaoachen98
> 
> I attempted to download 27,092 videos using the [panda.csv](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/blob/main/user_download/panda.csv) file, but only 15,537 videos were successfully downloaded.
> 
> I'm looking forward to _the one zip file_.

Same!

**Comment by Wiselnn570** [comment]
@linzhiqiu @geonm The clipped panda video is already available at [https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/tree/main/zip_folder/panda](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/tree/main/zip_folder/panda),
Please feel free to use it.
